### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by bdshibly** [gomex/docker-zabbix#14]
Hi,

I am getting the following error message 

/usr/bin/sudo /etc/zabbix/docker_stats.py
Traceback (most recent call last):
  File "/etc/zabbix/docker_stats.py", line 4, in <module>
    from docker_service import DockerService
ImportError: No module named docker_service

Please help
Ferdous Shibly

**Comment by osnet** [comment]
just copy the  directory  docker_service  in the rootfolder of zabbix > /etc/zabbix

**Comment by shkadov** [comment]
Hello,

Got the following:

# /usr/bin/sudo /etc/zabbix/docker_stats.py
Traceback (most recent call last):
  File "/etc/zabbix/docker_stats.py", line 4, in <module>
    from docker_service import DockerService
  File "/etc/zabbix/docker_service/DockerService.py", line 5, in <module>
    from docker import Client
  File "/usr/lib/python2.7/site-packages/docker/__init__.py", line 6, in <module>
    from .client import Client, AutoVersionClient, from_env # flake8: noqa
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 5, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from .packages.urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 95, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'requests.packages.urllib3'

Please advice
Den
